DiffDat <- OverallDat %>% group_by(ID) %>% arrange(ID,team)%>% 
  mutate('team2' = team, 'SeedTwo' = Seed2, "Seed3" = Seed2) %>%
  summarize(Season = Season[1],
            Round = Round[1],
            SeedLoc = SeedLoc[1],
            team = team[1],
            team2 = team2[2],
            Seed1 = Seed2[1],
            Seed2 = SeedTwo[2],
            DSeed = ifelse(Seed3[1] - Seed3[2] > 0, 1,0),
            DOutcome = ifelse(Outcome[1] > Outcome[2], 1, 0),
            DPts = ifelse(MedPts[1] - MedPts[2] > 0, 1, 0),
            DsdPts = ifelse(sdPts[1] - sdPts[2] > 0, 1, 0),
            DFG = ifelse(FGPct[1] - FGPct[2] > 0, 1, 0),
            DFG3 = ifelse(FGPct3[1] - FGPct3[2] > 0, 1, 0),
            DFT = ifelse(FTPct[1] - FTPct[2] > 0, 1, 0),
            DOR = ifelse(MedOR[1] - MedOR[2] > 0, 1, 0),
            DDR = ifelse(MedDR[1] - MedDR[2] > 0, 1, 0),
            DAst = ifelse(MedAst[1] - MedAst[2] > 0, 1, 0),
            DTO = ifelse(MedTO[1] - MedTO[2] > 0, 1, 0),
            DSTL = ifelse(MedSTL[1] - MedSTL[2] > 0, 1, 0),
            DBLK = ifelse(MedBLK[1] - MedBLK[2] > 0, 1, 0),
            DPF = ifelse(MedPF[1] - MedPF[2] > 0, 1, 0),
            DLast10 = ifelse(Last10[1] - Last10[2] > 0, 1, 0),
            DRecord = ifelse(PercentRecord[1] - PercentRecord[2] > 0, 1, 0),
            DOppRec = ifelse(OpponentRecord[1] - OpponentRecord[2] > 0,1,0),
            DPtDiff = ifelse(MedPtDiff[1] - MedPtDiff[2] > 0, 1, 0),
            DTPercent = ifelse(TPercent[1] - TPercent[2] > 0, 1, 0),
            DTGames = ifelse(TGames[1] - TGames[2] > 0, 1, 0),
            DAdjEM = AdjEM[1] - AdjEM[2],
            DAdjO = AdjO[1] - AdjO[2],
            DAdjD = AdjD[1] - AdjD[2],
            DAdjT = AdjT[1] - AdjT[2],
            DOAdjEM = OAdjEM[1] - OAdjEM[2],
            DOAdjO = OAdjO[1] - OAdjO[2],
            DOAdjD = OAdjD[1] - OAdjD[2]) %>%
  select(-ID) %>% na.omit() %>% filter(DSeed != -15, DSeed != 15, DSeed != 14, DSeed != -14)
View(DiffDat)


#########################################################################
DiffCombo <- EachCombo2 %>% mutate(DSeed = ifelse(Seed2.x - Seed2.y > 0, 1, 0),
                                   Seed1 = Seed2.x,
                                   Seed2 = Seed2.y,
                                   SeedLoc = SeedLoc.x,
                                   DPts = ifelse(MedPts.x - MedPts.y> 0, 1, 0),
                                   DsdPts = ifelse(sdPts.x - sdPts.y> 0, 1, 0),
                                   DFG = ifelse(FGPct.x - FGPct.y> 0, 1, 0),
                                   DFG3 = ifelse(FGPct3.x - FGPct3.y> 0, 1, 0),
                                   DFT = ifelse(FTPct.x - FTPct.y> 0, 1, 0),
                                   DOR = ifelse(MedOR.x - MedOR.y> 0, 1, 0),
                                   DDR = ifelse(MedDR.x - MedDR.y> 0, 1, 0),
                                   DAst = ifelse(MedAst.x - MedAst.y> 0, 1, 0),
                                   DTO = ifelse(MedTO.x - MedTO.y> 0, 1, 0),
                                   DSTL = ifelse(MedSTL.x - MedSTL.y> 0, 1, 0),
                                   DBLK = ifelse(MedBLK.x - MedBLK.y> 0, 1, 0),
                                   DPF = ifelse(MedPF.x - MedPF.y> 0, 1, 0),
                                   DLast10 = ifelse(Last10.x - Last10.y> 0, 1, 0),
                                   DRecord = ifelse(PercentRecord.x - PercentRecord.y> 0, 1, 0),
                                   DOppRec = ifelse(OpponentRecord.x - OpponentRecord.y> 0, 1, 0),
                                   DPtDiff = ifelse(MedPtDiff.x - MedPtDiff.y> 0, 1, 0),
                                   DTPercent = ifelse(TPercent.x - TPercent.y> 0, 1, 0),
                                   DTGames = ifelse(TGames.x - TGames.y> 0, 1, 0),
                                   DAdjEM = AdjEM.x - AdjEM.y,
                                   DAdjO = AdjO.x - AdjO.y,
                                   DAdjD = AdjD.x - AdjD.y,
                                   DAdjT = AdjT.x - AdjT.y,
                                   DOAdjEM = OAdjEM.x - OAdjEM.y,
                                   DOAdjO = OAdjO.x - OAdjO.y,
                                   DOAdjD = OAdjD.x - OAdjD.y) %>%
  select(-(Seed.x:SeedLoc.y), -(AdjEM.y:OAdjD.y)) %>% ungroup() %>%
  mutate('DTPercent' = ifelse(is.na(DTPercent), 0, DTPercent),
         'DTGames' = ifelse(is.na(DTGames), 0, DTGames),
         "DFT" = ifelse(is.na(DFT), 0, DFT))

######################## Continuous Variables ############################
######## Getting Difference of each matchup in the tournaments

DiffDat <- OverallDat %>% group_by(ID) %>% arrange(ID,team)%>% 
  mutate('team2' = team, 'SeedTwo' = Seed2, "Seed3" = Seed2) %>%
  summarize(Season = Season[1],
            Round = Round[1],
            team = team[1],
            team2 = team2[2],
            Seed1 = Seed2[1],
            Seed2 = SeedTwo[2],
            DSeedN = Seed3[1] - Seed3[2],
            DSeed = ifelse(Seed3[1] - Seed3[2] > 0, 1,0),
            DOutcome = ifelse(Outcome[1] > Outcome[2], 1, 0),
            DPts = MedPts[1] - MedPts[2],
            DsdPts = sdPts[1] - sdPts[2],
            DFG = FGPct[1] - FGPct[2],
            DFG3 = FGPct3[1] - FGPct3[2],
            DFT = FTPct[1] - FTPct[2],
            DOR = MedOR[1] - MedOR[2],
            DDR = MedDR[1] - MedDR[2],
            DAst = MedAst[1] - MedAst[2],
            DTO = MedTO[1] - MedTO[2],
            DSTL = MedSTL[1] - MedSTL[2],
            DBLK = MedBLK[1] - MedBLK[2],
            DPF = MedPF[1] - MedPF[2],
            DLast10 = Last10[1] - Last10[2],
            DRecord = PercentRecord[1] - PercentRecord[2],
            DOppRec = OpponentRecord[1] - OpponentRecord[2],
            DPtDiff = MedPtDiff[1] - MedPtDiff[2],
            DTPercent = TPercent[1] - TPercent[2],
            DTGames = TGames[1] - TGames[2],
            DAdjEM = AdjEM[1] - AdjEM[2],
            DAdjO = AdjO[1] - AdjO[2],
            DAdjD = AdjD[1] - AdjD[2],
            DAdjT = AdjT[1] - AdjT[2],
            DOAdjEM = OAdjEM[1] - OAdjEM[2],
            DOAdjO = OAdjO[1] - OAdjO[2],
            DOAdjD = OAdjD[1] - OAdjD[2],
            Dratio1 = (AdjD[1]/(OAdjO[1] + .001)) - 
              (AdjD[2]/(OAdjO[2] + .001)),
            Dratio2 = (AdjO[1]/(OAdjD[1] + .001)) - 
              (AdjO[2]/(OAdjD[2] + .001)),
            Dratio3 = MedAst[1]/MedTO[1] - MedAst[2]/MedTO[2]) %>%
  select(-ID) %>% na.omit()


DiffCombo <- EachCombo2 %>% mutate(DSeedN = Seed2.x - Seed2.y,
                                   DSeed = ifelse(Seed2.x - Seed2.y > 0, 1, 0),
                                   Seed1 = Seed2.x,
                                   Seed2 = Seed2.y,
                                   SeedLoc = SeedLoc.x,
                                   DPts = MedPts.x - MedPts.y,
                                   DsdPts = sdPts.x - sdPts.y,
                                   DFG = FGPct.x - FGPct.y,
                                   DFG3 = FGPct3.x - FGPct3.y,
                                   DFT = FTPct.x - FTPct.y,
                                   DOR = MedOR.x - MedOR.y,
                                   DDR = MedDR.x - MedDR.y,
                                   DAst = MedAst.x - MedAst.y,
                                   DTO = MedTO.x - MedTO.y,
                                   DSTL = MedSTL.x - MedSTL.y,
                                   DBLK = MedBLK.x - MedBLK.y,
                                   DPF = MedPF.x - MedPF.y,
                                   DLast10 = Last10.x - Last10.y,
                                   DRecord = PercentRecord.x - PercentRecord.y,
                                   DOppRec = OpponentRecord.x - OpponentRecord.y,
                                   DPtDiff = MedPtDiff.x - MedPtDiff.y,
                                   DTPercent = TPercent.x - TPercent.y,
                                   DTGames = TGames.x - TGames.y,
                                   DAdjEM = AdjEM.x - AdjEM.y,
                                   DAdjO = AdjO.x - AdjO.y,
                                   DAdjD = AdjD.x - AdjD.y,
                                   DAdjT = AdjT.x - AdjT.y,
                                   DOAdjEM = OAdjEM.x - OAdjEM.y,
                                   DOAdjO = OAdjO.x - OAdjO.y,
                                   DOAdjD = OAdjD.x - OAdjD.y,
                                   Dratio1 = (AdjD.x/(OAdjO.x + .001)) - 
                                     (AdjD.y/(OAdjO.y + .001)),
                                   Dratio2 = (AdjO.x/(OAdjD.x + .001)) - 
                                     (AdjO.y/(OAdjD.y + .001)),
                                   Dratio3 = MedAst.x/MedTO.x - MedAst.y/MedTO.y)%>%
  select(-(Seed.x:SeedLoc.y),-(AdjEM.y:OAdjD.y)) %>% ungroup() %>%
  mutate('DTPercent' = ifelse(is.na(DTPercent), 0, DTPercent),
         'DTGames' = ifelse(is.na(DTGames), 0, DTGames),
         "DFT" = ifelse(is.na(DFT), 0, DFT))

